// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppSettings 是会落盘的应用设置。
 * 字段使用 json tag，是为了让 Wails 返回给前端时直接得到 camelCase 数据。
 */
export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (!("petCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["petCount"] = 0;
        }
        if (!("maxPets" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxPets"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

/**
 * AppSettingsChangedEvent 会广播给所有 WebView，让设置窗口和宠物窗口保持一致。
 */
export class AppSettingsChangedEvent {
    /**
     * Creates a new AppSettingsChangedEvent instance.
     * @param {Partial<AppSettingsChangedEvent>} [$$source = {}] - The source object to create the AppSettingsChangedEvent.
     */
    constructor($$source = {}) {
        if (!("petCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["petCount"] = 0;
        }
        if (!("maxPets" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxPets"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettingsChangedEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettingsChangedEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettingsChangedEvent(/** @type {Partial<AppSettingsChangedEvent>} */($$parsedSource));
    }
}

/**
 * PetVisualsChangedEvent 用于通知所有宠物窗口重新读取本地图片缓存。
 */
export class PetVisualsChangedEvent {
    /**
     * Creates a new PetVisualsChangedEvent instance.
     * @param {Partial<PetVisualsChangedEvent>} [$$source = {}] - The source object to create the PetVisualsChangedEvent.
     */
    constructor($$source = {}) {
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PetVisualsChangedEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PetVisualsChangedEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PetVisualsChangedEvent(/** @type {Partial<PetVisualsChangedEvent>} */($$parsedSource));
    }
}
