// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppSettings 是会落盘的应用设置。
 * 字段使用 json tag，是为了让 Wails 返回给前端时直接得到 camelCase 数据。
 */
export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (!("petCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["petCount"] = 0;
        }
        if (!("maxPets" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxPets"] = 0;
        }
        if (!("shortcuts" in $$source)) {
            /**
             * @member
             * @type {ShortcutSettings}
             */
            this["shortcuts"] = (new ShortcutSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("shortcuts" in $$parsedSource) {
            $$parsedSource["shortcuts"] = $$createField2_0($$parsedSource["shortcuts"]);
        }
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

/**
 * AppSettingsChangedEvent 会广播给所有 WebView，让设置窗口和宠物窗口保持一致。
 */
export class AppSettingsChangedEvent {
    /**
     * Creates a new AppSettingsChangedEvent instance.
     * @param {Partial<AppSettingsChangedEvent>} [$$source = {}] - The source object to create the AppSettingsChangedEvent.
     */
    constructor($$source = {}) {
        if (!("petCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["petCount"] = 0;
        }
        if (!("maxPets" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxPets"] = 0;
        }
        if (!("shortcuts" in $$source)) {
            /**
             * @member
             * @type {ShortcutSettings}
             */
            this["shortcuts"] = (new ShortcutSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettingsChangedEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettingsChangedEvent}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("shortcuts" in $$parsedSource) {
            $$parsedSource["shortcuts"] = $$createField2_0($$parsedSource["shortcuts"]);
        }
        return new AppSettingsChangedEvent(/** @type {Partial<AppSettingsChangedEvent>} */($$parsedSource));
    }
}

/**
 * PetVisualsChangedEvent 用于通知所有宠物窗口重新读取本地图片缓存。
 */
export class PetVisualsChangedEvent {
    /**
     * Creates a new PetVisualsChangedEvent instance.
     * @param {Partial<PetVisualsChangedEvent>} [$$source = {}] - The source object to create the PetVisualsChangedEvent.
     */
    constructor($$source = {}) {
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PetVisualsChangedEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PetVisualsChangedEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PetVisualsChangedEvent(/** @type {Partial<PetVisualsChangedEvent>} */($$parsedSource));
    }
}

/**
 * ShortcutSettings 保存用户可配置的行为快捷键。
 * 支持 CmdOrCtrl 作为跨平台修饰键；默认快捷键使用 Ctrl+Alt，避免和常见 Cmd 快捷键冲突。
 */
export class ShortcutSettings {
    /**
     * Creates a new ShortcutSettings instance.
     * @param {Partial<ShortcutSettings>} [$$source = {}] - The source object to create the ShortcutSettings.
     */
    constructor($$source = {}) {
        if (!("idle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["idle"] = "";
        }
        if (!("edgeWander" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["edgeWander"] = "";
        }
        if (!("followMouse" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["followMouse"] = "";
        }
        if (!("cycle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cycle"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShortcutSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ShortcutSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShortcutSettings(/** @type {Partial<ShortcutSettings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ShortcutSettings.createFrom;
