// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PetService 暴露给前端设置窗口调用。
 * 前端通过 Wails runtime 的 Call.ByName 调用这些方法，不需要手写 IPC。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.AppSettings>}
 */
export function GetSettings() {
    return $Call.ByID(1191198805).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function NotifyVisualSettingsChanged() {
    return $Call.ByID(3541967712);
}

/**
 * @param {number} count
 * @returns {$CancellablePromise<$models.AppSettings>}
 */
export function SetPetCount(count) {
    return $Call.ByID(3923387084, count).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.ShortcutSettings} shortcuts
 * @returns {$CancellablePromise<$models.AppSettings>}
 */
export function SetShortcuts(shortcuts) {
    return $Call.ByID(3925119199, shortcuts).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.AppSettings.createFrom;
